apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-argo
spec:
  selector:
    matchLabels:
      app: myapp-argo
  replicas: 2
  template:
    metadata:
      labels:
        app: myapp-argo
    spec:
      containers:
      - name: myapp-argo
        image: htalukder/openshift-hello
        ports:
        - containerPort: 8080
