apiVersion: v1
kind: Service
metadata:
  name: myapp-external-service
spec:
  type: LoadBalancer
  selector:
    app: myapp-argo
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 35010
  
